index:
   path: /
   controller: App\Controller\DefaultController::index
   methods: GET

app_register:
  path: /register
  controller: App\Controller\RegistrationController::register
  methods: GET|POST
