home:
   path: /
   controller: App\Controller\HomeController::index
   methods: GET
   
about:
   path: /about-us
   controller: App\Controller\HomeController::aboutUs
   methods: GET

contact_us:
   path: /contact-us
   controller: App\Controller\HomeController::contactUs
   methods: GET

login:
   path: /login
   controller: App\Controller\LoginController::login
   methods: GET

reset_password:
   path: /login/reset-password
   controller: App\Controller\LoginController::renderResetPasswordPage
   methods: GET

app_reset_password:
   path: /login/reset-password
   controller: App\Controller\LoginController::resetPassword
   methods: POST

feed:
   path: /feed
   controller: App\Controller\FeedController::index
   methods: GET

form_post:
   path: /add-post
   controller: App\Controller\FeedController::createPost
   methods: GET

edit_post:
   path: /post/{id}/edit-post
   controller: App\Controller\FeedController::editPost
   methods: GET|POST

edit_comment:
   path: /comment/{id}/edit-comment
   controller: App\Controller\FeedController::editComment
   methods: GET|POST

add_post:
   path: /add-post
   controller: App\Controller\FeedController::createPost
   methods: POST

remove_post:
   path: /post/{id}/remove-post
   controller: App\Controller\FeedController::removePost
   methods: GET

add_comment:
   path: /post/{id}/add-comment
   controller: App\Controller\FeedController::createComment
   methods: POST|GET

remove_comment:
   path: /comment/{id}/remove-comment
   controller: App\Controller\FeedController::removeComment
   methods: POST|GET

add_friend:
   path: /dog/{id}/add-friend
   controller: App\Controller\PackController::addFriend
   methods: GET

remove_friend:
   path: /dog/{id}/remove-friend
   controller: App\Controller\PackController::removeFriend
   methods: GET

profile:
   path: /profile
   controller: App\Controller\ProfileController::index
   methods: GET

packs:
   path: /packs
   controller: App\Controller\GroupsController::index
   methods: GET

notifications:
   path: /notifications
   controller: App\Controller\NotificationsController::index
   methods: GET

register:
   path: /register
   controller: App\Controller\RegistrationController::index
   methods: GET

welcome:
   path: /register/welcome
   controller: App\Controller\RegistrationController::renderRegisterWelcomePage
   methods: GET

app_register:
  path: /register
  controller: App\Controller\RegistrationController::register
  methods: POST

app_login:
   path: /login
   controller: App\Controller\LoginController::login
   methods: POST

logout:
   path: /logout
   controller: App\Controller\LoginController::logout
   methods: GET



