home:
   path: /
   controller: App\Controller\HomeController::renderHomeLandingPage
   methods: GET
   
about:
   path: /about
   controller: App\Controller\HomeController::renderAboutPage
   methods: GET

contact_us:
   path: /contact_us
   controller: App\Controller\HomeController::renderContactUsPage
   methods: GET

login:
   path: /login
   controller: App\Controller\LoginController::index
   methods: GET

register:
   path: /register
   controller: App\Controller\RegisterController::index
   methods: GET

app_register:
  path: /register
  controller: App\Controller\RegistrationController::register
  methods: POST

app_login:
   path: /login
   controller: App\Controller\LoginController::login
   methods: POST



